Repository the-purgatory/sc-app, pull requests merged in 2020-03, with the labels that each got.

#6 moved github docs to .github folder
  .github/CODE_OF_CONDUCT.md
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
Labels: documentation

#3 added husky, prettier and eslint prettier plugin
  .eslintignore
  .eslintrc
  .eslintrc.js
  .prettierrc
  .prettierrc.js
  App.js
  README.md
  babel.config.js
  index.js
  metro.config.js
  package.json
  yarn.lock
Labels: documentation, enhancement

#10 Create pr-labeler.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
Labels: feature

#11 Create main.yml
  .github/workflows/release-drafter.yml
Labels: fix

#16 added random and documentations tag to release drafter
  .github/pr-labeler.yml
  .github/release-drafter.yml
Labels: misc

#14 fix/readme-update-with-wiki
  README.md
Labels: fix

#17 feature/styledComponents - styled components added
  .eslintrc
  App.js
  __tests__/App-test.js
  package.json
  yarn.lock
Labels: feature

#22 added codeclimate
  .codeclimate.yml
Labels: feature

#24 styled component style changes and eslint config change
  .eslintrc
  App.js
  package.json
  yarn.lock
Labels: misc

#26 Update pr-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: fix

#27 Update README.md
  README.md
Labels: documentation

#31 feature/feature--setup-redux-store
  .eslintrc
  App.js
  package.json
  src/actions/index.js
  src/components/Login.js
  src/reducers/auth.js
  src/store/index.js
  yarn.lock
Labels: feature
